### ISSUE TITLE
When insert backlink then click on backlink suggestion menu, the backlink not insert into DataLoom

### ISSUE THREAD

**Issue by funamorisenji** [trey-wallis/obsidian-dataloom#737] opened 2023-09-11 18:21 UTC
### Describe the bug

When I tried to insert a backlink inside the Loom. It's not working as I expect. 

- [[]] is not auto complete 
- When click backlink suggestion , nothing happen. It should insert the backlink I click.

### Steps to reproduce

1. Create a Data Loom table 
2. Insert the backlink inside the Loom 
3. Click on any suggestion on the backlink suggestion 
4. The backlink is not present in the Loom, so you have to type it by yourself to get the correct backlink.

https://github.com/trey-wallis/obsidian-dataloom/assets/38547838/5bc0932c-d2d7-4058-83b9-f66d6670d3a2

### Expected behavior

Get the backlink that click on the backlink suggestion 

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.5
	Installer version: v1.3.3
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 22.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Atom v0.0.0
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 66
	Plugins enabled: 57
		1: Templater v1.16.0
		2: Timelines v0.3.2
		3: Admonition v10.0.1
		4: Advanced Tables v0.19.1
		5: Better footnote v1.0.1
		6: Better Word Count v0.10.0
		7: Checklist v2.2.12
		8: Dataview v0.5.56
		9: Citations v0.4.5
		10: Highlightr v1.2.2
		11: Hotkeys++ v0.2.7
		12: HTML Tags Autocomplete v0.0.7
		13: Obsidian Git v2.22.0
		14: Sort & Permute lines v0.7.0
		15: Image Toolkit v1.4.0
		16: Advanced Slides v1.20.0
		17: Mind Map v1.1.0
		18: Kanban v1.5.3
		19: Dynamic Table of Contents v0.0.27
		20: Copy button for code blocks v0.1.0
		21: Zotero Integration v3.0.9
		22: Footnote Shortcut v0.1.3
		23: Readwise Official v2.0.1
		24: Typewriter Scroll v0.2.2
		25: Influx v2.1.2
		26: Natural Language Dates v0.6.1
		27: DataLoom v8.4.1
		28: Excel to Markdown Table v0.4.0
		29: Minimal Theme Settings v7.2.2
		30: Tag Wrangler v0.5.12
		31: Focus Mode v1.11.4
		32: Novel word count v2.23.4
		33: Editor Syntax Highlight v0.1.3
		34: Sync Graph Settings v1.1.0
		35: Colored Text v0.5.0
		36: Canvas Filter v0.9.2
		37: Regex Find/Replace v1.2.0
		38: CSV Table v1.2.0
		39: Link Headers Directly v1.0.2
		40: Reading Time v1.1.1
		41: Ozan's Image in Editor Plugin v2.2.4
		42: Global Search and Replace v0.3.0
		43: Any Block v2.2.0
		44: MathLive v1.0.1
		45: Tracker v1.10.9
		46: Excalidraw v1.9.19
		47: Obsidian Math+ v0.5.1
		48: Diagrams.net v1.0.4
		49: Better CodeBlock v1.0.8
		50: Advanced Codeblock v1.1.5
		51: Projects v1.16.3
		52: ePub Reader v1.0.2
		53: Google Calendar v1.10.4
		54: Latex Suite v1.7.4
		55: Calendar v1.5.10
		56: Icon Folder v2.2.1
		57: Rollover Daily Todos v1.1.7

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by vineetg3** [comment] 2023-09-17 22:56
I am facing the same bug as well

**Comment by trey-wallis** [comment] 2023-09-25 17:31
@funamorisenji Thanks for finding this. This seems to be a regression. I will add it to road map

**Comment by trey-wallis** [comment] 2023-10-29 23:58
Fixed in 8.8.0.

**Closed by trey-wallis** 2023-10-29 23:58 UTC
Labels: bug
